const crypto = require('crypto');
const jwt = require('jsonwebtoken');
const LocalInstallation = require('../../models/localInstallation.model');
const SyncConflict = require('../../models/syncConflict.model');
const Hospital = require('../../models/hospital.model');

const JWT_SECRET = process.env.JWT_SECRET || 'med365_local_agent_secret_key_2026';
const HEARTBEAT_TIMEOUT_MS = 45000; // 45 seconds without heartbeat = OFFLINE

class LocalAgentService {
    /**
     * Generate or refresh a pairing token for Hospital Admin setup
     */
    async provisionInstallation(hospitalId, customName = '') {
        const hospital = await Hospital.findById(hospitalId).select('name slug').lean();
        if (!hospital) {
            throw new Error('Hospital not found.');
        }

        let installation = await LocalInstallation.findOne({ hospitalId });

        if (!installation) {
            const randomCode = crypto.randomBytes(3).toString('hex').toUpperCase();
            const installationId = `MED365-LOCAL-${randomCode}`;
            installation = new LocalInstallation({
                hospitalId,
                installationId,
                name: customName || `${hospital.name} Server`
            });
        } else if (customName) {
            installation.name = customName;
        }

        // Generate 6-char alphanumeric pairing code
        const pairingToken = crypto.randomBytes(3).toString('hex').toUpperCase();
        const expiresAt = new Date(Date.now() + 30 * 60 * 1000); // 30 minutes

        installation.pairingToken = pairingToken;
        installation.pairingTokenExpiresAt = expiresAt;

        installation.operationalLogs.unshift({
            timestamp: new Date(),
            level: 'INFO',
            event: 'PAIRING_TOKEN_GENERATED',
            message: `Pairing token generated by hospital admin for ${installation.installationId}`
        });

        // Cap logs at 50 entries
        if (installation.operationalLogs.length > 50) {
            installation.operationalLogs = installation.operationalLogs.slice(0, 50);
        }

        await installation.save();

        return {
            installationId: installation.installationId,
            pairingToken,
            expiresAt,
            name: installation.name,
            hospitalId: hospital._id,
            hospitalName: hospital.name
        };
    }

    /**
     * Pair Local Agent with Cloud using one-time Pairing Token
     */
    async pairAgent({ installationId, pairingToken, agentVersion = '1.0.0', metrics = {}, ipAddress = '' }) {
        if (!installationId || !pairingToken) {
            throw new Error('installationId and pairingToken are required.');
        }

        const installation = await LocalInstallation.findOne({
            installationId: String(installationId).trim().toUpperCase()
        });

        if (!installation) {
            throw new Error('Invalid installation ID.');
        }

        if (!installation.pairingToken || installation.pairingToken !== String(pairingToken).trim().toUpperCase()) {
            throw new Error('Invalid or expired pairing token.');
        }

        if (new Date() > new Date(installation.pairingTokenExpiresAt)) {
            throw new Error('Pairing token has expired. Please generate a new one from Hospital Admin.');
        }

        const hospital = await Hospital.findById(installation.hospitalId).select('name slug isActive').lean();
        if (!hospital || !hospital.isActive) {
            throw new Error('Associated hospital is inactive or suspended.');
        }

        // Issue permanent Agent JWT
        const agentPayload = {
            installationId: installation.installationId,
            hospitalId: String(installation.hospitalId),
            role: 'local_agent',
            iat: Math.floor(Date.now() / 1000)
        };
        const agentToken = jwt.sign(agentPayload, JWT_SECRET, { expiresIn: '365d' });
        const agentTokenHash = crypto.createHash('sha256').update(agentToken).digest('hex');

        // Burn one-time token and update status
        installation.pairingToken = null;
        installation.pairingTokenExpiresAt = null;
        installation.agentTokenHash = agentTokenHash;
        installation.agentVersion = agentVersion || '1.0.0';
        installation.status = 'ONLINE';
        installation.cloudConnection = 'CONNECTED';
        installation.lastHeartbeat = new Date();
        installation.lastIp = ipAddress || '';
        if (metrics) {
            installation.localHealth = {
                ...installation.localHealth,
                ...metrics
            };
        }

        installation.operationalLogs.unshift({
            timestamp: new Date(),
            level: 'INFO',
            event: 'AGENT_PAIRED',
            message: `Local Agent v${agentVersion} successfully authenticated and paired with Cloud.`
        });

        if (installation.operationalLogs.length > 50) {
            installation.operationalLogs = installation.operationalLogs.slice(0, 50);
        }

        await installation.save();

        return {
            success: true,
            installationId: installation.installationId,
            hospitalId: String(installation.hospitalId),
            hospitalName: hospital.name,
            agentToken
        };
    }

    /**
     * Authenticate and verify an incoming Agent request (Heartbeat or Ping)
     */
    verifyAgentToken(token) {
        if (!token) {
            throw new Error('No agent token provided.');
        }
        const cleanToken = token.startsWith('Bearer ') ? token.slice(7) : token;
        try {
            const decoded = jwt.verify(cleanToken, JWT_SECRET);
            if (decoded.role !== 'local_agent') {
                throw new Error('Invalid token scope: not a local agent.');
            }
            return {
                decoded,
                tokenHash: crypto.createHash('sha256').update(cleanToken).digest('hex')
            };
        } catch (err) {
            throw new Error(`Agent authentication failed: ${err.message}`);
        }
    }

    /**
     * Process Heartbeat from Local Agent
     */
    async processHeartbeat({ token, installationId, dbStatus, status, agentVersion, metrics = {}, outboxStats = null, ipAddress = '' }) {
        const { decoded, tokenHash } = this.verifyAgentToken(token);

        if (decoded.installationId !== installationId) {
            throw new Error('Token installation ID mismatch.');
        }

        const installation = await LocalInstallation.findOne({
            installationId: decoded.installationId,
            hospitalId: decoded.hospitalId
        });

        if (!installation) {
            throw new Error('Installation not found on cloud.');
        }

        if (installation.agentTokenHash !== tokenHash) {
            throw new Error('Agent token has been revoked or replaced.');
        }

        const previousDbStatus = installation.dbStatus;
        const normalizedDbStatus = ['HEALTHY', 'DOWN'].includes(dbStatus) ? dbStatus : 'UNKNOWN';
        const isDbHealthy = normalizedDbStatus === 'HEALTHY';

        installation.lastHeartbeat = new Date();
        installation.lastIp = ipAddress || installation.lastIp;
        installation.agentVersion = agentVersion || installation.agentVersion;
        installation.dbStatus = normalizedDbStatus;
        installation.cloudConnection = 'CONNECTED';
        installation.status = isDbHealthy ? 'ONLINE' : 'DEGRADED';

        if (metrics) {
            installation.localHealth = {
                dbLatencyMs: Number(metrics.dbLatencyMs) || 0,
                memoryMb: Number(metrics.memoryMb) || 0,
                uptimeSeconds: Number(metrics.uptimeSeconds) || 0,
                nodeVersion: String(metrics.nodeVersion || ''),
                platform: String(metrics.platform || ''),
                localDbName: String(metrics.localDbName || 'medical365_local')
            };
        }

        if (outboxStats) {
            if (!installation.syncStatus) installation.syncStatus = {};
            if (!installation.syncStatus.uploadStatus) installation.syncStatus.uploadStatus = {};

            if (outboxStats.pending !== undefined) installation.syncStatus.uploadStatus.pendingUploadsCount = outboxStats.pending;
            if (outboxStats.syncing !== undefined) installation.syncStatus.uploadStatus.syncingUploadsCount = outboxStats.syncing;
            if (outboxStats.completed !== undefined) installation.syncStatus.uploadStatus.completedUploadsCount = outboxStats.completed;
            if (outboxStats.failed !== undefined) installation.syncStatus.uploadStatus.failedUploadsCount = outboxStats.failed;
            if (outboxStats.conflicts !== undefined) installation.syncStatus.uploadStatus.conflictsCount = outboxStats.conflicts;
            if (outboxStats.completedToday !== undefined) installation.syncStatus.uploadStatus.completedTodayCount = outboxStats.completedToday;
            if (outboxStats.lastSuccessfulSyncAt) installation.syncStatus.uploadStatus.lastSuccessfulSyncAt = new Date(outboxStats.lastSuccessfulSyncAt);
        }

        // Log DB health transition if changed
        if (previousDbStatus !== normalizedDbStatus) {
            installation.operationalLogs.unshift({
                timestamp: new Date(),
                level: isDbHealthy ? 'INFO' : 'ERROR',
                event: 'LOCAL_DB_STATUS_CHANGED',
                message: `Local MongoDB health changed from ${previousDbStatus} to ${normalizedDbStatus}`
            });
        }

        if (installation.operationalLogs.length > 50) {
            installation.operationalLogs = installation.operationalLogs.slice(0, 50);
        }

        await installation.save();

        return {
            success: true,
            acknowledged: true,
            status: installation.status,
            dbStatus: installation.dbStatus,
            serverTime: Date.now()
        };
    }

    /**
     * Get Installation Status for Hospital Admin UI
     */
    async getStatus(hospitalId) {
        const installation = await LocalInstallation.findOne({ hospitalId }).lean();
        if (!installation) {
            return {
                configured: false,
                status: 'NOT_CONFIGURED',
                dbStatus: 'UNKNOWN',
                cloudConnection: 'DISCONNECTED',
                installationId: null,
                agentVersion: null,
                lastHeartbeat: null,
                operationalLogs: []
            };
        }

        // Dynamically compute real-time connection state based on lastHeartbeat freshness
        const now = Date.now();
        const lastHbTime = installation.lastHeartbeat ? new Date(installation.lastHeartbeat).getTime() : 0;
        const isHeartbeatFresh = (now - lastHbTime) < HEARTBEAT_TIMEOUT_MS;

        let computedStatus = installation.status;
        let computedCloud = installation.cloudConnection;

        if (!installation.agentTokenHash) {
            computedStatus = 'NOT_CONFIGURED';
            computedCloud = 'DISCONNECTED';
        } else if (!isHeartbeatFresh) {
            computedStatus = 'OFFLINE';
            computedCloud = 'DISCONNECTED';
        }

        const isPairingActive = installation.pairingToken && installation.pairingTokenExpiresAt && new Date() < new Date(installation.pairingTokenExpiresAt);

        let pendingConflictsCount = 0;
        try {
            pendingConflictsCount = await SyncConflict.countDocuments({
                hospitalId,
                status: { $in: ['PENDING', 'PENDING_REVIEW'] }
            });
        } catch (e) {
            console.error('[LocalAgentService.getStatus] Error counting conflicts:', e.message);
        }

        return {
            configured: Boolean(installation.agentTokenHash),
            installationId: installation.installationId,
            name: installation.name,
            agentVersion: installation.agentVersion,
            status: computedStatus,
            dbStatus: isHeartbeatFresh ? installation.dbStatus : 'UNKNOWN',
            cloudConnection: computedCloud,
            lastHeartbeat: installation.lastHeartbeat,
            heartbeatAgeSeconds: lastHbTime ? Math.round((now - lastHbTime) / 1000) : null,
            localHealth: isHeartbeatFresh ? installation.localHealth : null,
            isPairingActive,
            pairingToken: isPairingActive ? installation.pairingToken : null,
            pairingExpiresAt: isPairingActive ? installation.pairingTokenExpiresAt : null,
            pendingConflictsCount,
            operationalLogs: (installation.operationalLogs || []).slice(0, 20)
        };
    }

    /**
     * Test Connection from Hospital Admin UI
     */
    async testConnection(hospitalId) {
        const status = await this.getStatus(hospitalId);
        if (!status.configured) {
            return {
                success: false,
                status: 'NOT_CONFIGURED',
                message: 'Local Agent is not yet paired or configured for this hospital.'
            };
        }

        if (status.status === 'OFFLINE') {
            return {
                success: false,
                status: 'OFFLINE',
                message: `Local Agent is currently offline. Last heartbeat was ${status.heartbeatAgeSeconds || 'unknown'} seconds ago.`
            };
        }

        return {
            success: true,
            status: status.status,
            dbStatus: status.dbStatus,
            cloudConnection: status.cloudConnection,
            latencyMs: status.localHealth?.dbLatencyMs || 0,
            lastHeartbeat: status.lastHeartbeat,
            message: `Local Agent is connected and operational. Local MongoDB is ${status.dbStatus}.`
        };
    }

    /**
     * Revoke installation credentials
     */
    async revokeInstallation(hospitalId) {
        const installation = await LocalInstallation.findOne({ hospitalId });
        if (!installation) {
            return { success: true };
        }

        installation.agentTokenHash = null;
        installation.pairingToken = null;
        installation.pairingTokenExpiresAt = null;
        installation.status = 'NOT_CONFIGURED';
        installation.dbStatus = 'UNKNOWN';
        installation.cloudConnection = 'DISCONNECTED';

        installation.operationalLogs.unshift({
            timestamp: new Date(),
            level: 'WARN',
            event: 'INSTALLATION_REVOKED',
            message: 'Installation credentials revoked by Hospital Admin.'
        });

        await installation.save();

        return {
            success: true,
            message: 'Local Agent credentials revoked. The agent will no longer be able to authenticate.'
        };
    }
}

module.exports = new LocalAgentService();
